//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.27 at 11:47:11 AM IST 
//


package edu.yaksha.fiboapp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Fibonacci complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Fibonacci">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="serial-number" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="fibonacci-number" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Fibonacci", propOrder = {
    "serialNumber",
    "fibonacciNumber"
})
public class Fibonacci {

    @XmlElement(name = "serial-number")
    protected int serialNumber;
    @XmlElement(name = "fibonacci-number")
    protected int fibonacciNumber;

    /**
     * Gets the value of the serialNumber property.
     * 
     */
    public int getSerialNumber() {
        return serialNumber;
    }

    /**
     * Sets the value of the serialNumber property.
     * 
     */
    public void setSerialNumber(int value) {
        this.serialNumber = value;
    }

    /**
     * Gets the value of the fibonacciNumber property.
     * 
     */
    public int getFibonacciNumber() {
        return fibonacciNumber;
    }

    /**
     * Sets the value of the fibonacciNumber property.
     * 
     */
    public void setFibonacciNumber(int value) {
        this.fibonacciNumber = value;
    }

}
